Bugfix: new save_magfield3 should respect directory in same element
KATRIN-Experiment/Kassiopeia pull request #44
Opened 2021-01-23 22:16 UTC by wdconinc

In configurations such as
```xml
<electromagnet_field
    name="magnetic_field_electromagnet"
    directory="[KEMFIELD_CACHE]"
    save_magfield3="true"
    file="ProtonTrapMagnets.kbd"
    system="world/proton_trap"
    spaces="world/proton_trap/@magnet_tag"
>
```
the mag3 files are not saved in the directory immediately above. This is counter-intuitive, but even worse when using docker or singularity containers it defaults to a non-writable location. This also affects some examples, such as DipoleTrapSimulation.xml.

This pull request introduces a public getter for the directory (and file) of the underlying `KStaticElectromagnetField` which is then used by `KGStaticElectromagnetField` to instruct `KGElectromagnetConverter` to write to the directory location.

This pull request also ensures that failure to open the file for writing is flagged as a warning but does not cause Kassiopeia to shut down with a stack trace.

2021-01-25 08:32 UTC, zykure commented
Thanks for pointing out this issue. The feature was mainly intended for debugging and I missed the fact that it writes to a non-standard location. I agree that it should use one of the KEMField directories.

However, since the Magfield3 dump is not strictly a cache file it should not be written to the cache path, which is what one usually specifies for `directory` in `electromagnet_field`. By convention it makes more sense to put this file into the scratch path. The downside is that it needs another option in the XML builder, but that can be optional and default to `SCRATCH_DEFAULT_DIR`.

Would you adapt your pull request accordingly?

2021-01-25 15:20 UTC, wdconinc commented
Sure, I can modify it to accept an xml attribute `directory_magfield3`. I probably will be for next weekend due to teaching this week.

2021-02-22 00:39 UTC, wdconinc commented
Attribute `directory_magfield3` is now implemented. This also explicitly initializes `fSaveMagfield3` to true. I had to merge master into the branch to get it to compile with my c++17 ROOT.

Nothing specified (default):
```
[KEMFIELD NORMAL MESSAGE] Saving magfield3 geometry to file: /usr/local/Kassiopeia/git/scratch/KEMField/magnetic_field_electromagnet.mag3
```

`directory_magfield3=/tmp/` specified:
```
[KEMFIELD NORMAL MESSAGE] Saving magfield3 geometry to file: /tmp/magnetic_field_electromagnet.mag3
```

2021-02-22 10:52 UTC, zykure requested changes

2021-02-22 10:52 UTC, zykure commented on KEMField/Source/Interface/KGeoBag/src/KGElectromagnetConverter.cc
> +        if (fMagfield3File->IsOpen()) {
I think this should also check for nullptr since it might not be initialized at this point: `if (fMagfield3File && fMagfield3File->IsOpen())`

2021-02-22 14:59 UTC, zykure approved these changes

2021-02-22 15:01 UTC, merged