Fix compiler warnings from MagfieldCoils
KATRIN-Experiment/Kassiopeia pull request #86
Opened 2023-11-21 09:46 UTC by richeldichel

As reported in issue #84 there appear many compiler warnings when building MagfieldCoils.cxx (mostly [-Wmisleading-indentation] and [-Wunused-variable]. 

This pull request removes the warnings and further applies .clang-format to MagfieldCoils.cxx and MagfieldCoils.h

2023-11-21 13:02 UTC, 2xB requested changes
- [ ] It is quite difficult to understand which variables are member variables and which are local. I would suggest refactoring member variables to the common naming scheme in Kassiopeia, being `fVariableName`.
- [ ] Is it correct to return "true" in the functions if `nmax` is 0? Shouldn't that raise an error? Also, I think it is redundant to have an inner counting variable like `int i` that is followed by an outer counting variable `int nmax`, but that maybe doesn't matter that much.
- [ ] Can one remove https://github.com/KATRIN-Experiment/Kassiopeia/blob/4cca8e75612c507b3dd182b08443694dc4344761/KEMField/Source/ExternalFields/MagfieldCoils/CMakeLists.txt#L42 now?

2024-05-08 14:23 UTC, 2xB commented
Nice! I did the last remaining open point according to an answer Ferenc wrote back then (nmax <= 1 can't be used, nmax=500 is recommended, so it now throws a corresponding error in case of nmax <= 1).
Since I was a bit fast committing using the web IDE, there are two amends as separate commits, which I have to apologize for.

2024-05-08 14:24 UTC, 2xB approved these changes

2024-06-07 13:48 UTC, richeldichel commented
> Nice! I did the last remaining open point according to an answer Ferenc wrote back then (nmax <= 1 can't be used, nmax=500 is recommended, so it now throws a corresponding error in case of nmax <= 1). Since I was a bit fast committing using the web IDE, there are two amends as separate commits, which I have to apologize for.

Thanks! I squashed your two additional commits so that this pull request can now also be finally merged.

2024-06-07 13:48 UTC, merged